# Generated by Django 5.1 on 2024-08-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="done",
        ),
    ]
